from pydantic import BaseModel, Field


class ScheduledActivity(BaseModel):
    """
    One activity placed into a specific
    day and sequence position.
    """

    name: str

    day_number: int = Field(
        ge=1,
    )

    sequence: int = Field(
        ge=1,
    )

    estimated_duration_minutes: int = Field(
        ge=1,
    )

    travel_from_previous_minutes: float = Field(
        default=0,
        ge=0,
    )

    preference_score: float = Field(
        ge=0,
        le=1,
    )

    environment: str


class OptimizedDay(BaseModel):
    """
    Optimized activities for one travel day.
    """

    day_number: int = Field(
        ge=1,
    )
    weather_suitability: str | None = None

    activities: list[ScheduledActivity] = Field(
        default_factory=list,
    )

    total_activity_cost: float = Field(
        default=0,
        ge=0,
    )

    total_activity_minutes: int = Field(
        default=0,
        ge=0,
    )

    total_travel_minutes: float = Field(
        default=0,
        ge=0,
    )


class OptimizedItinerary(BaseModel):
    """
    Result generated by the OR-Tools optimizer.
    """

    destination: str

    days: list[OptimizedDay] = Field(
        default_factory=list,
    )

    selected_activities: list[str] = Field(
        default_factory=list,
    )

    dropped_activities: list[str] = Field(
        default_factory=list,
    )

    total_activity_cost: float = Field(
        default=0,
        ge=0,
    )

    activity_budget: float | None = Field(
        default=None,
        ge=0,
    )

    objective_value: float | None = None